name: Terraform Docs
on:
  issue_comment:
    types: [created]

jobs:
  terraform_docs:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/tfdoc')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head


      - name: Render terraform docs inside the README.md and push changes back to PR branch
        id: tf-docs
        uses: terraform-docs/gh-actions@v1.4.0
        with:
          output-file: README.md
          output-method: inject
          find-dir: infrastructure/modules
          indention: 4

      - name: Add reaction to comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          # Add a reaction to the comment to indicate the action has completed
          reactions: 'rocket'
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.comment.id }}
          token: ${{ secrets.GITHUB_TOKEN }}
