name: Terraform Docs
on:
  issue_comment:
    types: [created]

jobs:
  terraform_docs:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/tfdoc')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:

      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        id: tf-docs
        uses: terraform-docs/gh-actions@v1.4.0
        with:
          output-file: README.md
          output-method: inject
          find-dir: infrastructure/modules
          git-push: true
          indention: 4

      - name: Add reaction to comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          # Add a reaction to the comment to indicate the action has completed
          reactions: 'rocket'
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.comment.id }}
          token: ${{ secrets.GITHUB_TOKEN }}
